name: manajemen_keuangan_transaksi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.4
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Verdana
      fonts:
        - asset: assets/fonts/verdana.ttf
        - asset: assets/fonts/verdana-bold.ttf
          weight: 700
        - asset: assets/fonts/verdana-bold-italic.ttf
          weight: 700
          style: italic
